### ISSUE TITLE
Failed to load the grunt-runner package

### ISSUE THREAD

**Issue by yurique** [nickclaw/atom-grunt-runner#47]
[Enter steps to reproduce below:]

1. Just install `grunt-runner` package

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [grunt-runner](https://github.com/nickclaw/atom-grunt-runner) package, v0.8.0

### Stack Trace

Failed to load the grunt-runner package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/yurique/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:1:1)
  at /Users/yurique/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:15:5
  at Object.<anonymous> (/Users/yurique/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:311:5)
  at Object.<anonymous> (/Users/yurique/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/yurique/.atom/packages/grunt-runner/lib/grunt-runner.coffee:8:15)
  at Object.<anonymous> (/Users/yurique/.atom/packages/grunt-runner/lib/grunt-runner.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:665:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:174:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:166:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:85:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -1:45.4 core:cancel (atom-text-editor.editor.mini)
     -1:45.0 editor:consolidate-selections (atom-text-editor.editor)
     -1:45.0 core:cancel (atom-text-editor.editor)
  2x -1:44.5 core:move-up (atom-text-editor.editor)
     -1:38.7 settings-view:open (atom-text-editor.editor)
     -1:01.5 application:open (atom-text-editor.editor)
     -1:00.1 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:56.7 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:56.7 core:cancel (atom-text-editor.editor.mini)
     -0:56.1 command-palette:toggle (atom-text-editor.editor)
     -0:54.7 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:54.7 core:cancel (atom-text-editor.editor.mini)
 10x -0:53.0 core:move-up (atom-text-editor.editor)
     -0:50.5 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -0:49.0 settings-view:open (atom-text-editor.editor)
     -0:44.4 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
grunt-runner, v0.8.0
language-scala, v1.1.0
react, v0.11.4
react-snippets, v0.1.4

# Dev
No dev packages
```

**Comment by kokarn** [comment]
Is this still an issue?
