### ISSUE TITLE
atom.tooltips.add Issue

### ISSUE THREAD

**Issue by kupoback** [nickclaw/atom-grunt-runner#51]
I updated the package today and was welcomed with this error

`Error: setTooltip is no longer available. Please use 'atom.tooltips.add' instead.

See the docs at https://atom.io/docs/api/latest/TooltipManager#instance-add
  at [object Object].$.fn.setTooltip (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:611:11)
  
at ResultsView.module.exports.ResultsView.initialize (C:\Users\nick\.atom\packages\grunt-runner\lib\grunt-runner-view.coffee:47:23)
  
at ResultsView.View (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:184:25)
  
  at new ResultsView (C:\Users\nick\.atom\packages\grunt-runner\lib\grunt-runner-view.coffee:16:5)
 
 at Object.module.exports.activate (C:\Users\nick\.atom\packages\grunt-runner\lib\grunt-runner.coffee:16:21)
  
at Package.module.exports.Package.activateNow (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:222:19)
  
at C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:203:30
  
at Package.module.exports.Package.measure (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:147:15)
  
at Package.module.exports.Package.activate (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package.js:195:14)
  
at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\src\package-manager.js:434:21)
  
at C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:316:29
  
at exit (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
  
at triggerExitCallback (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\src\buffered-process.js:213:47)
  
at ChildProcess.<anonymous> (C:\Users\nick\AppData\Local\atom\app-0.196.0\resources\app.asar\src\buffered-process.js:235:18)
  
at emitTwo (events.js:87:13)
  
at ChildProcess.emit (events.js:169:7)
  
at Process.ChildProcess._handle.onexit (child_process.js:1057:12)`

**Comment by kokarn** [comment]
This has already been fixed with https://github.com/nickclaw/atom-grunt-runner/commit/02ef94c5913f88f338cb1ff4f0b5d90fb738b162. 
Just waiting for @nickclaw to publish a new version. 
Until then you can get the working version from this repository.
