### ISSUE TITLE
Failed to activate the grunt-runner package

### ISSUE THREAD

**Issue by kupoback** [nickclaw/atom-grunt-runner#54]
I just updated atom to 0.199.0

    ReferenceError: path is not defined
    at ResultsView.module.exports.ResultsView.parseGruntFile (C:\Users\nick\.atom\packages\grunt-runner\lib\grunt-runner-view.coffee:70:44) 
    at Config.module.exports.Config.observeKeyPath (C:\Users\nick\AppData\Local\atom\app-     0.199.0\resources\app.asar\src\config.js:555:7)
    at Config.module.exports.Config.observe (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\config.js:135:21)
    at Object.module.exports.activate (C:\Users\nick\.atom\packages\grunt-runner\lib\grunt-runner.coffee:19:21)
    at Package.module.exports.Package.activateNow (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:238:19)
    at C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:219:30
    at Package.module.exports.Package.measure (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:163:15)
    at Package.module.exports.Package.activate (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\package-manager.js:435:21)
    at C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:345:29
    at exit (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:41:16)
    at triggerExitCallback (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\nick\AppData\Local\atom\app-0.199.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

`Windows 8.1`

      "*":
    "exception-reporting":
      userId: "9e35bb78-8916-1f07-64b9-e607dcb71fea"
    welcome:
      showOnStartup: false
    linter:
      lintOnChangeMethod: "throttle"
      showInfoMessages: true
      statusBar: "Show error of the selected line"
    editor:
      fontSize: 11
      invisibles:
        {}
      zoomFontWhenCtrlScrolling: false
      tabLength: 4
       softWrap: true
    "grunt-runner":
      {}
    core:
      audioBeep: false
      disabledPackages: []
    emmet:
      {}
    "file-icons":
      {}
    "autocomplete-plus":
      confirmCompletion: "enter"
    fonts:
      fontFamily: "Source Code Pro Extra Light"
    minimap:
      scrollAnimation: true
      useHardwareAcceleration: false
    "remote-sync":
      {}
    tabs:
      showIcons: false
      alwaysShowTabBar: false
    notifications:
      showErrorsInDevMode: true
    "filetype-color":
      enabled: "false"
    "linter-jshint":
      {}

**Comment by kokarn** [comment]
Maybe something you can have a look at @sebastianhaeni ?

**Comment by sebastianhaeni** [comment]
I'm currently unable to test a possible fix as I'm on vacation.
This might do the trick:
`path = require 'path'`

**Comment by kokarn** [comment]
Apparently, the latest version of atom (0.199.0) has this little snippet
>Fixed an issue where ```fs``` and ```path``` would be accidentally available as global variables

I'll fix this ASAP
