### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by Mortoc** [nickclaw/atom-grunt-runner#60]
[Enter steps to reproduce below:]

1. This happens every time I run Atom with grunt-runner installed

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [grunt-runner](https://github.com/nickclaw/atom-grunt-runner) package, v0.11.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/mortoc/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:187

TypeError: undefined is not a function
  at ResultsView.module.exports.ResultsView.colorize (/Users/mortoc/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:187:17)
  at ResultsView.module.exports.ResultsView.addLine (/Users/mortoc/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:163:17)
  at Task.callback (/Users/mortoc/.atom/packages/grunt-runner/lib/grunt-runner-view.coffee:96:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:68:72
  at Task.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:81:31)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at handleMessage (child_process.js:306:10)
  at Pipe.channel.onread (child_process.js:334:11)

```

### Commands

```
     -0:39.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:39.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:34.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:30.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:30.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:29.8.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:14.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {},
  "grunt-runner": {}
}
```

### Installed Packages

```coffee
# User
jsformat, v0.9.0
pretty-json, v0.4.1

# Dev
No dev packages
```

**Comment by kokarn** [comment]
Could you update grunt-runner to latest version and see if the problem still occurs?
